# -*- coding: utf-8 -*-
"""Swin Inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lF8qZ-incTJrOfcPnWDa9DZIonrlTXM4
"""

!pip3 install openmim
!mim install mmcv-full

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/open-mmlab/mmdetection.git
# %cd mmdetection
!pip install -e .

!python -c 'import torch; print(torch.cuda.is_available())'
!python -c 'import mmcv; import mmcv.ops'

from google.colab import drive
drive.mount('/content/drive/')

from mmdet.apis import init_detector, inference_detector, show_result_pyplot
import mmcv

config_file = '/content/mmdetection/configs/swin/mask_rcnn_swin-t-p4-w7_fpn_fp16_ms-crop-3x_coco.py'
checkpoint_file = '/content/drive/MyDrive/Colab Notebooks/cam2/Swin-T FP16/mask_rcnn_swin-t-p4-w7_fpn_fp16_ms-crop-3x_coco_20210908_165006-90a4008c.pth'

model = init_detector(config_file, checkpoint_file, device='cuda:0')

img = '/content/mmdetection/demo/demo.jpg'
result = inference_detector(model, img)

show_result_pyplot(model, img, result)